### PR TITLE
I2CDev / MPU6050 libs incompatibility build error fix

### PR DESCRIPTION
**Pull request by pppedrillo**
The I2CDev and MPU6050 libraries used in the project are not compatible with the latest PlatformIO lib registry and thus cause build error (see attached screenshot) with the latest PlatformIO core v5.2.4 /expressif8266 platform v3.2.0

The examples of failure : 
https://github.com/universam1/iSpindel/runs/4592717524?check_suite_focus=true
https://github.com/universam1/iSpindel/runs/4759700794?check_suite_focus=true

Capture

These changes include both 2 libs as a part of the project (as advised on PIO and by libs author https://github.com/jrowberg/i2cdevlib ) and thus fix the building error. 

Built firmware tested on device **OK**

### CODE REVIEW

**Comment by thegreatgunbantoad** [comment]
How on earth does an update in PlatformIO lead to the need for 26 file changes!  What did the PlatformIO guys do!?

**Comment by pppedrillo** [comment]
> How on earth does an update in PlatformIO lead to the need for 26 file changes! What did the PlatformIO guys do!?

**It is not "26 files changes"** , but rather **"1 file changed + 25 files added"**

Briefly : 
 Up to PlatformIO 3 (2.6.3 the latest) all the platform libs (including those 25 files) are getting downloaded automatically during  the build. You can see em all in your .pio/libdeps/<your_target> folder. 
Since PlatformIO 3 PIO handle a registry of packages and I2Cdev libs is not adapted to be included into this registry, thus are not downloaded during the build (only their .piopm and json, but not the sources) - thus no headers and build failed.

If you really interested in this, you can find all the info in PIO docs.

It is mostly I2Cdev lib developer's fault -  he has not adapted his lib to be included into PIO registry. If you check i2CDev repo, you'll see it was last time updated 2-3 years ago. PIO encouraged all the shareholders to make changes for upcoming migration in 2019.

**Comment by pppedrillo** [comment]
@thegreatgunbantoad 
Capture

**Comment by thegreatgunbantoad** [comment]
@pppedrillo thanks for the info.  Quite interesting.  Nice job figuring out what needed to get sorted.  Well done.

**Review by universam1 — APPROVED** [review]
Thanks 👍
Looks like we have no better option for now

**Pull request merged**
