### PR TITLE
Increased the maximum size of the polynomial parameter

### PR DESCRIPTION
**Pull request by niki77**
Increased the maximum size of the polynomial parameter from 100 to 250 char

### CODE REVIEW

**Review by ErikdBr — CHANGES_REQUESTED** [review]
I reviewed the change, it looks ok.

**Comment by ErikdBr** [comment]
What usually seems to be forgotten is to increase line 23 #define FIRMWAREVERSION "6.5.0" in the globals.h
or is that only to be done by @universam1 ?

**Comment by thegreatgunbantoad** [comment]
I'd be inclined to change the 250 in:
`WiFiManagerParameter custom_polynom("POLYN", "Polynominal", htmlencode(my_polynominal).c_str(), 250 * 2, WFM_NO_LABEL);`
to
`sizeof(my_polynominal)
So as to reduce the amount of hard coding

But it's functionally fine as is.

**Review by universam1 — APPROVED** [review]
:+1:

**Pull request merged**
