### PR TITLE
Adding support of Brewblox using MQTT

### PR DESCRIPTION
**Pull request by bdelbosc**
Hi, this PR extends the iSpindel firmware in order to support the Brewblox application
cheers
ben

### CODE REVIEW

**Comment by thegreatgunbantoad** [comment]
1 very minor comment on the following line:
    sender.add("Gravity[degP]", Gravity);
Gravity could be plato or sg, without checking the setting you can't be sure

**Comment by bdelbosc** [comment]
> Gravity could be plato or sg, without checking the setting you can't be sure
Thanks, you are right and I think there is no way to know the unit, I changed to "Gravity"

**Comment by thegreatgunbantoad** [comment]
> > Gravity could be plato or sg, without checking the setting you can't be sure
> 
> Thanks, you are right and I think there is no way to know the unit, I changed to "Gravity"

No your right, there isn't, it's down to how you calculate the polynomial

**Comment by bdelbosc** [comment]
:wave: any chance to get a code review or a merge status soon? Thx

**Comment by bdelbosc** [comment]
FYI, the last update is to align code with the master branch

**Comment by bdelbosc** [comment]
Hi, @universam1 I would like your feedback on this because if this cannot be merged I have to maintain another project to be able to use an iSpindel from Brewblox. Thanks.

**Comment by bdelbosc** [comment]
:wave: @universam1 any chance to get feedback? Thx

**Comment by bdelbosc** [comment]
Hi, I hope you are safe @universam1, 
FYI I am sharing the firmware release matching my PR here:
https://github.com/bdelbosc/iSpindel/releases/tag/6.4.0-brewblox

**Comment by bdelbosc** [comment]
PR aligned on master, removing conflict on version

**Review by universam1 — APPROVED** [review]
Lgtm

**Comment by Nixon506E** [comment]
So happy to have this added! I am just wondering if this allows for multiple iSpindels by passing a name as well or if that can be added, thanks!

**Comment by Nixon506E** [comment]
Can we get this updated to use the websocket connection that brewblox already exposes at wss://brewblox.local:443/eventbus instead of having to expose mqtt

**Pull request merged**
