### PR TITLE
Add github actions ci

### PR DESCRIPTION
**Pull request by MarcoCLA**

### CODE REVIEW

**Review by universam1 — APPROVED** [review]
Excellent

**Comment by universam1** [comment]
That’s excellent. didn’t find time for yet so thanks alot!

**Comment by thegreatgunbantoad** [comment]
For those of us following along and not quite as knowledgeable.  What does this actually do?

**Comment by FernandoGarcia** [comment]
Hi @MarcoCLA!
Can you tell the python version to compile the code correctly?
I can't compile with Python 3.7. I'm getting this errors:

```
File "git_rev.py", line 5
    print(f'\'-D FIRMWAREVERSION="{version}"\'')
                                              ^
SyntaxError: invalid syntax
OSError: 'python git_rev.py' exited 1:
  File "/home/fernandogarcia/.platformio/penv/lib/python3.7/site-packages/platformio/builder/main.py", line 177:
    env.SConscript("$BUILD_SCRIPT")
  File "/home/fernandogarcia/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Script/SConscript.py", line 591:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/fernandogarcia/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Script/SConscript.py", line 280:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/home/fernandogarcia/.platformio/platforms/espressif8266/builder/main.py", line 238:
    target_elf = env.BuildProgram()
  File "/home/fernandogarcia/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Util.py", line 658:
    return self.method(*nargs, **kwargs)
  File "/home/fernandogarcia/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/platformio.py", line 61:
    env.ProcessProgramDeps()
  File "/home/fernandogarcia/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Util.py", line 658:
    return self.method(*nargs, **kwargs)
  File "/home/fernandogarcia/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/platformio.py", line 124:
    env.ProcessFlags(env.get("BUILD_FLAGS"))
  File "/home/fernandogarcia/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Util.py", line 658:
    return self.method(*nargs, **kwargs)
  File "/home/fernandogarcia/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/platformio.py", line 222:
    env.Append(**env.ParseFlagsExtended(flags))
  File "/home/fernandogarcia/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Util.py", line 658:
    return self.method(*nargs, **kwargs)
  File "/home/fernandogarcia/.platformio/penv/lib/python3.7/site-packages/platformio/builder/tools/platformio.py", line 185:
    for key, value in env.ParseFlags(str(raw)).items():
  File "/home/fernandogarcia/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Environment.py", line 821:
    do_parse(arg)
  File "/home/fernandogarcia/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Environment.py", line 673:
    arg = self.backtick(arg[1:])
  File "/home/fernandogarcia/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Environment.py", line 585:
    raise OSError("'%s' exited %d" % (command, status))
```
Best regards.

**Comment by pppedrillo** [comment]
> Can you tell me the python version to compile the code correctly?
> I can't compile with Python 3.7. I'm getting this errors:
> 
> ```
> File "git_rev.py", line 5
>     print(f'\'-D FIRMWAREVERSION="{version}"\'')
>                                               ^
> SyntaxError: invalid syntax
> OSError: 'python git_rev.py' exited 1:
>   File "/home/fernandogarcia/.platformio/penv/lib/python3.7/site-packages/platformio/builder/main.py", line 177:
>     env.SConscript("$BUILD_SCRIPT")

You need version 3.8 or newer

**Pull request merged**
