### PR TITLE
Patch for Blynk API for better accuracy

### PR DESCRIPTION
**Pull request by MatthBou**
A problem happens when data are sending to Blynk and using the specific gravity.

The specific gravity value is rounded only two digits after the decimal point, which takes away from the precision.
for example :

specific gravity read by the iSpindel: 1.052
specific gravity sent to blynk: 1.05

Thank you for the work done, this project is really awesome!

### CODE REVIEW

**Review by thegreatgunbantoad — APPROVED** [review]
Whilst I can't check that this works using Blynk, it's a pretty simple change and it certainly compiles.
Looks good to me.

**Review by gdolling — APPROVED** [review]
I have tested this change with blynk. Works as expected and is a good improvement. Gravity really needs 3dp.

image_6483441 (1)

**Comment by MatthBou** [comment]
@gdolling  thank's for your feedback!

**Review by universam1 — APPROVED** [review]
:+1:

**Pull request merged**
